// Practical Nepali phrases for the recall course, grouped by topic.
// Array order inside a topic is the canonical teaching order (most useful first);
// a fresh profile's intro seed reshuffles it per user.
//
// Conventions (enforced by tools/generate-characters.mjs):
// - glyph: NFC Devanagari, at least two words; statements end with ।,
//   questions with ?, punctuation only sentence-final; numbers spelled out.
// - roman: hand-written in the words-group scheme — schwa retained (ṭhīka),
//   macrons ā/ī/ū, retroflex dots ṭ/ḍ/ṇ/ṣ, w for व, chh for छ, ṁ for anusvara,
//   nasalized vowels with a tilde (kahā̃, hũ); spaces and ? kept, no danda.
// - meaning: lowercase english, standalone "I" allowed.

export const TOPICS = [
    {id: 'greetings', label: 'Greetings & politeness', phrases: [
        ['नमस्ते हजुर।', 'namaste hajura', 'hello (polite)'],
        ['सञ्चै हुनुहुन्छ?', 'sañchai hunuhunchha?', 'how are you?'],
        ['म सञ्चै छु।', 'ma sañchai chhu', 'I am fine'],
        ['तपाईंलाई कस्तो छ?', 'tapāīṁlāī kasto chha?', 'how is it going for you?'],
        ['के छ खबर?', 'ke chha khabara?', 'what is the news?'],
        ['सबै ठीक छ।', 'sabai ṭhīka chha', 'everything is fine'],
        ['धेरै धन्यवाद।', 'dherai dhanyawāda', 'thank you very much'],
        ['स्वागत छ।', 'swāgata chha', 'welcome'],
        ['माफ गर्नुहोस्।', 'māpha garnuhos', 'excuse me, sorry'],
        ['केही छैन।', 'kehī chhaina', 'it is nothing, no problem'],
        ['फेरि भेटौँला।', 'pheri bheṭaũlā', 'see you again'],
        ['भोलि भेटौँला।', 'bholi bheṭaũlā', 'see you tomorrow'],
        ['पछि भेटौँला।', 'pachhi bheṭaũlā', 'see you later'],
        ['भित्र आउनुहोस्।', 'bhitra āunuhos', 'please come in'],
        ['बस्नुहोस् न।', 'basnuhos na', 'please have a seat'],
        ['चिया खानुहोस् न।', 'chiyā khānuhos na', 'please have some tea'],
        ['यहाँ आउनुहोस्।', 'yahā̃ āunuhos', 'please come here'],
        ['एकछिन पर्खनुहोस्।', 'ekachhina parkhanuhos', 'please wait a moment'],
        ['ढिलो भएकोमा माफ गर्नुहोस्।', 'ḍhilo bhaekomā māpha garnuhos', 'sorry for being late'],
        ['कुनै समस्या छैन।', 'kunai samasyā chhaina', 'no problem at all'],
        ['तपाईंलाई पनि।', 'tapāīṁlāī pani', 'same to you'],
        ['शुभ यात्रा।', 'shubha yātrā', 'have a good trip'],
        ['शुभ रात्रि।', 'shubha rātri', 'good night'],
        ['मीठो मानेर खानुहोस्।', 'mīṭho mānera khānuhos', 'enjoy your meal'],
        ['फेरि आउनुहोस् है।', 'pheri āunuhos hai', 'please come again'],
    ]},
    {id: 'basics', label: 'Basics & responses', phrases: [
        ['ठीक छ।', 'ṭhīka chha', 'okay, fine'],
        ['हुन्छ हजुर।', 'hunchha hajura', 'yes, sure (polite)'],
        ['त्यो हुँदैन।', 'tyo hũdaina', 'that will not do'],
        ['मलाई थाहा छ।', 'malāī thāhā chha', 'I know'],
        ['मलाई थाहा छैन।', 'malāī thāhā chhaina', "I don't know"],
        ['मैले बुझेँ।', 'maile bujhẽ', 'I understood'],
        ['म बुझ्दिनँ।', 'ma bujhdinã', "I don't understand"],
        ['फेरि भन्नुहोस् न।', 'pheri bhannuhos na', 'please say it again'],
        ['बिस्तारै भन्नुहोस् न।', 'bistārai bhannuhos na', 'please speak slowly'],
        ['मलाई नेपाली अलिअलि आउँछ।', 'malāī nepālī aliali āũchha', 'I speak a little nepali'],
        ['यसलाई नेपालीमा के भनिन्छ?', 'yasalāī nepālīmā ke bhaninchha?', 'what is this called in nepali?'],
        ['अङ्ग्रेजीमा भन्नुहोस् न।', 'aṅgrejīmā bhannuhos na', 'please say it in english'],
        ['यसको अर्थ के हो?', 'yasako artha ke ho?', 'what does this mean?'],
        ['यो मलाई चाहिन्छ।', 'yo malāī chāhinchha', 'I need this'],
        ['मलाई चाहिँदैन।', 'malāī chāhĩdaina', "I don't need it"],
        ['म सक्छु।', 'ma sakchhu', 'I can'],
        ['म सक्दिनँ।', 'ma sakdinã', 'I cannot'],
        ['एकदम राम्रो।', 'ekadama rāmro', 'very good'],
        ['मलाई केही सोध्नु छ।', 'malāī kehī sodhnu chha', 'I have something to ask'],
        ['सहयोग गर्नुहोस् न।', 'sahayoga garnuhos na', 'please help me'],
        ['समस्या भयो।', 'samasyā bhayo', 'there is a problem'],
        ['केही चाहिँदैन।', 'kehī chāhĩdaina', 'nothing is needed'],
        ['पर्दैन हजुर।', 'pardaina hajura', 'no need (polite)'],
        ['अलिअलि मात्र।', 'aliali mātra', 'just a little'],
        ['होला नि।', 'holā ni', 'probably so'],
    ]},
    {id: 'shopping', label: 'Money & shopping', phrases: [
        ['यो कति हो?', 'yo kati ho?', 'how much is this?'],
        ['यो कति पर्छ?', 'yo kati parchha?', 'how much does this cost?'],
        ['धेरै महँगो भयो।', 'dherai mahãgo bhayo', 'that got too expensive'],
        ['अलि सस्तो गर्नुहोस् न।', 'ali sasto garnuhos na', 'please make it a bit cheaper'],
        ['अलि घटाउनुहोस् न।', 'ali ghaṭāunuhos na', 'please lower the price a bit'],
        ['अन्तिम दाम कति?', 'antima dāma kati?', 'what is the final price?'],
        ['ठीक दाम भन्नुहोस्।', 'ṭhīka dāma bhannuhos', 'tell me the fair price'],
        ['बढी भयो हजुर।', 'baḍhī bhayo hajura', 'that is too much'],
        ['खुद्रा पैसा छ?', 'khudrā paisā chha?', 'do you have change?'],
        ['खुद्रा छैन।', 'khudrā chhaina', 'I have no change'],
        ['म यो लिन्छु।', 'ma yo linchhu', "I'll take this"],
        ['मलाई त्यो देखाउनुहोस् न।', 'malāī tyo dekhāunuhos na', 'please show me that one'],
        ['अर्को छ?', 'arko chha?', 'is there another one?'],
        ['ठूलो साइज छ?', 'ṭhūlo sāija chha?', 'is there a bigger size?'],
        ['सानो साइज छ?', 'sāno sāija chha?', 'is there a smaller size?'],
        ['एउटा दिनुहोस् न।', 'euṭā dinuhos na', 'one please'],
        ['दुईटा दिनुहोस् न।', 'duīṭā dinuhos na', 'two please'],
        ['आधा किलो दिनुहोस्।', 'ādhā kilo dinuhos', 'half a kilo please'],
        ['एक किलो कति हो?', 'eka kilo kati ho?', 'how much is one kilo?'],
        ['जम्मा कति भयो?', 'jammā kati bhayo?', 'how much in total?'],
        ['पैसा यहाँ तिर्ने हो?', 'paisā yahā̃ tirne ho?', 'do I pay here?'],
        ['कार्डले तिर्न मिल्छ?', 'kārḍale tirna milchha?', 'can I pay by card?'],
        ['रसिद दिनुहोस् न।', 'rasida dinuhos na', 'a receipt please'],
        ['यो मलाई मन पर्यो।', 'yo malāī mana paryo', 'I like this one'],
        ['यो मन परेन।', 'yo mana parena', "I don't like this one"],
        ['यो नयाँ हो?', 'yo nayā̃ ho?', 'is this new?'],
        ['पछि आउँछु।', 'pachhi āũchhu', "I'll come back later"],
        ['हेर्दै मात्र हुँ।', 'herdai mātra hũ', 'I am just looking'],
        ['पसल कति बजे खुल्छ?', 'pasala kati baje khulchha?', 'when does the shop open?'],
        ['पसल कति बजे बन्द हुन्छ?', 'pasala kati baje banda hunchha?', 'when does the shop close?'],
    ]},
    {id: 'time', label: 'Time & dates', phrases: [
        ['अहिले कति बज्यो?', 'ahile kati bajyo?', 'what time is it now?'],
        ['पाँच बज्यो।', 'pā̃cha bajyo', "it is five o'clock"],
        ['साढे पाँच बज्यो।', 'sāḍhe pā̃cha bajyo', 'it is half past five'],
        ['कति बेला जाने?', 'kati belā jāne?', 'what time shall we go?'],
        ['कहिले आउनुहुन्छ?', 'kahile āunuhunchha?', 'when will you come?'],
        ['म भोलि आउँछु।', 'ma bholi āũchhu', "I'll come tomorrow"],
        ['आज होइन भोलि।', 'āja hoina bholi', 'not today, tomorrow'],
        ['हिजो राति ढिलो भयो।', 'hijo rāti ḍhilo bhayo', 'it got late last night'],
        ['भोलि बिहान भेटौँला।', 'bholi bihāna bheṭaũlā', 'see you tomorrow morning'],
        ['आज बेलुका फुर्सद छ?', 'āja belukā phursada chha?', 'are you free this evening?'],
        ['खाना अघि आउनुहोस्।', 'khānā aghi āunuhos', 'come before the meal'],
        ['खाना पछि भेटौँला।', 'khānā pachhi bheṭaũlā', 'see you after the meal'],
        ['कक्षा अघि खाजा खाऔँ।', 'kakshā aghi khājā khāaũ', "let's have a snack before class"],
        ['एक घण्टा पछि आउनुहोस्।', 'eka ghaṇṭā pachhi āunuhos', 'come after one hour'],
        ['दस मिनेट पर्खनुहोस्।', 'dasa mineṭa parkhanuhos', 'wait ten minutes'],
        ['अलि ढिलो हुन्छ।', 'ali ḍhilo hunchha', 'it will be a bit late'],
        ['छिटो आउनुहोस् है।', 'chhiṭo āunuhos hai', 'please come quickly'],
        ['समय छैन हजुर।', 'samaya chhaina hajura', 'there is no time'],
        ['आज कुन बार हो?', 'āja kuna bāra ho?', 'what day is it today?'],
        ['आज शुक्रबार हो।', 'āja shukrabāra ho', 'today is friday'],
        ['शनिबार बिदा हुन्छ।', 'shanibāra bidā hunchha', 'saturday is the day off'],
        ['आज बन्द छ।', 'āja banda chha', 'it is closed today'],
        ['भोलि खुल्छ।', 'bholi khulchha', 'it opens tomorrow'],
        ['अहिले जाने बेला भयो।', 'ahile jāne belā bhayo', 'it is time to go now'],
        ['पर्सि फेरि आउँछु।', 'parsi pheri āũchhu', "I'll come again the day after tomorrow"],
        ['अस्ति आएको थिएँ।', 'asti āeko thiẽ', 'I came the day before yesterday'],
        ['कति समय लाग्छ?', 'kati samaya lāgchha?', 'how long does it take?'],
        ['आधा घण्टा लाग्छ।', 'ādhā ghaṇṭā lāgchha', 'it takes half an hour'],
        ['बिहान सबेरै उठ्छु।', 'bihāna saberai uṭhchhu', 'I get up early in the morning'],
        ['राति अबेर नसुत्नुहोस्।', 'rāti abera nasutnuhos', "don't stay up late at night"],
    ]},
    {id: 'directions', label: 'Directions & places', phrases: [
        ['शौचालय कहाँ छ?', 'shauchālaya kahā̃ chha?', 'where is the toilet?'],
        ['बाटो कता हो?', 'bāṭo katā ho?', 'which way is the road?'],
        ['बायाँतिर जानुहोस्।', 'bāyā̃tira jānuhos', 'go to the left'],
        ['दायाँतिर मोड्नुहोस्।', 'dāyā̃tira moḍnuhos', 'turn to the right'],
        ['सिधा जानुहोस्।', 'sidhā jānuhos', 'go straight'],
        ['यहाँबाट कति टाढा छ?', 'yahā̃bāṭa kati ṭāḍhā chha?', 'how far is it from here?'],
        ['नजिकै छ।', 'najikai chha', 'it is nearby'],
        ['धेरै टाढा छ।', 'dherai ṭāḍhā chha', 'it is very far'],
        ['हिँडेर जान मिल्छ?', 'hĩḍera jāna milchha?', 'can I walk there?'],
        ['अगाडि छ।', 'agāḍi chha', 'it is ahead'],
        ['पछाडि छ।', 'pachhāḍi chha', 'it is behind'],
        ['माथि जानुहोस्।', 'māthi jānuhos', 'go up'],
        ['तल झर्नुहोस्।', 'tala jharnuhos', 'go down'],
        ['चोकमा पुगेर सोध्नुहोस्।', 'chokamā pugera sodhnuhos', 'ask when you reach the square'],
        ['यो बाटो ठीक हो?', 'yo bāṭo ṭhīka ho?', 'is this the right way?'],
        ['म हराएँ।', 'ma harāẽ', 'I am lost'],
        ['नक्सा देखाउनुहोस् न।', 'naksā dekhāunuhos na', 'please show me on the map'],
        ['बजार कता पर्छ?', 'bajāra katā parchha?', 'which way is the market?'],
        ['यहाँ नजिक अस्पताल छ?', 'yahā̃ najika aspatāla chha?', 'is there a hospital nearby?'],
        ['मन्दिर कता छ?', 'mandira katā chha?', 'where is the temple?'],
        ['यो कुन ठाउँ हो?', 'yo kuna ṭhāũ ho?', 'what place is this?'],
        ['ठेगाना यहाँ लेखेको छ।', 'ṭhegānā yahā̃ lekheko chha', 'the address is written here'],
        ['पुल तरेर जानुहोस्।', 'pula tarera jānuhos', 'cross the bridge and go'],
        ['ढोका अगाडि पर्खनुहोस्।', 'ḍhokā agāḍi parkhanuhos', 'wait in front of the door'],
        ['भित्र जान मिल्छ?', 'bhitra jāna milchha?', 'may I go inside?'],
        ['बाहिर निस्कनुहोस्।', 'bāhira niskanuhos', 'go outside'],
        ['यहीँ बस्नुहोस्।', 'yahī̃ basnuhos', 'stay right here'],
        ['त्यहाँ नजानुहोस्।', 'tyahā̃ najānuhos', "don't go there"],
        ['कुन गल्लीबाट जाने?', 'kuna gallībāṭa jāne?', 'through which lane to go?'],
        ['मेरो होटल यतै छ।', 'mero hoṭala yatai chha', 'my hotel is around here'],
    ]},
    {id: 'transport', label: 'Transport', phrases: [
        ['यहाँ रोक्नुहोस् न।', 'yahā̃ roknuhos na', 'please stop here'],
        ['अगाडि रोक्नुहोस्।', 'agāḍi roknuhos', 'stop ahead'],
        ['मिटरमा जाने हो?', 'miṭaramā jāne ho?', 'will you go by the meter?'],
        ['कति लिनुहुन्छ?', 'kati linuhunchha?', 'how much will you take?'],
        ['धेरै भयो है।', 'dherai bhayo hai', 'that is too much'],
        ['रत्नपार्क जाने बस कुन हो?', 'ratnapārka jāne basa kuna ho?', 'which bus goes to ratnapark?'],
        ['यो बस कता जान्छ?', 'yo basa katā jānchha?', 'where does this bus go?'],
        ['भाडा कति हो?', 'bhāḍā kati ho?', 'how much is the fare?'],
        ['सिट खाली छ?', 'siṭa khālī chha?', 'is there a free seat?'],
        ['म यहीँ झर्छु।', 'ma yahī̃ jharchhu', 'I get off right here'],
        ['ढोका खोल्नुहोस् न।', 'ḍhokā kholnuhos na', 'please open the door'],
        ['जाम धेरै छ।', 'jāma dherai chha', 'the traffic jam is heavy'],
        ['बिस्तारै चलाउनुहोस् है।', 'bistārai chalāunuhos hai', 'please drive slowly'],
        ['विमानस्थल जानु छ।', 'wimānasthala jānu chha', 'I need to go to the airport'],
        ['कहिले छुट्छ?', 'kahile chhuṭchha?', 'when does it depart?'],
        ['कहिले पुगिन्छ?', 'kahile puginchha?', 'when do we arrive?'],
        ['अर्को बिसौनी कुन हो?', 'arko bisaunī kuna ho?', 'which is the next stop?'],
        ['यहाँ पार्किङ छ?', 'yahā̃ pārkiṅa chha?', 'is there parking here?'],
        ['पेट्रोल पम्प कता छ?', 'peṭrola pampa katā chha?', 'where is the fuel station?'],
        ['टिकट कहाँ किन्ने?', 'ṭikaṭa kahā̃ kinne?', 'where do I buy a ticket?'],
        ['दुई जनाको टिकट दिनुहोस्।', 'duī janāko ṭikaṭa dinuhos', 'two tickets please'],
        ['झोला माथि राख्नुहोस्।', 'jholā māthi rākhnuhos', 'put the bag on top'],
        ['ट्याक्सी बोलाउनुहोस् न।', 'ṭyāksī bolāunuhos na', 'please call a taxi'],
        ['बाटोमा समय कति लाग्छ?', 'bāṭomā samaya kati lāgchha?', 'how long is the ride?'],
        ['सुरक्षित यात्रा गर्नुहोस्।', 'surakshita yātrā garnuhos', 'travel safely'],
    ]},
    {id: 'food', label: 'Food & drink', phrases: [
        ['मेनु दिनुहोस् न।', 'menu dinuhos na', 'the menu please'],
        ['के के छ खानलाई?', 'ke ke chha khānalāī?', 'what is there to eat?'],
        ['दालभात एक प्लेट दिनुहोस्।', 'dālabhāta eka pleṭa dinuhos', 'one plate of dal bhat please'],
        ['मलाई चिया दिनुहोस्।', 'malāī chiyā dinuhos', 'tea for me please'],
        ['दूध चिया कि कालो?', 'dūdha chiyā ki kālo?', 'milk tea or black?'],
        ['चिनी नहाल्नुहोस्।', 'chinī nahālnuhos', 'no sugar please'],
        ['पानी दिनुहोस् न।', 'pānī dinuhos na', 'water please'],
        ['उमालेको पानी छ?', 'umāleko pānī chha?', 'do you have boiled water?'],
        ['धेरै पिरो नबनाउनुहोस्।', 'dherai piro nabanāunuhos', "don't make it too spicy"],
        ['पिरो कम गर्नुहोस्।', 'piro kama garnuhos', 'make it less spicy'],
        ['यो धेरै मीठो छ।', 'yo dherai mīṭho chha', 'this is very tasty'],
        ['म मासु खान्नँ।', 'ma māsu khānnã', "I don't eat meat"],
        ['शाकाहारी खाना छ?', 'shākāhārī khānā chha?', 'is there vegetarian food?'],
        ['अण्डा हाल्नुहोस् न।', 'aṇḍā hālnuhos na', 'please add an egg'],
        ['अरू केही चाहिँदैन।', 'arū kehī chāhĩdaina', 'nothing else needed'],
        ['अलिकति मात्र दिनुहोस्।', 'alikati mātra dinuhos', 'just a little please'],
        ['पुग्यो हजुर।', 'pugyo hajura', 'that is enough'],
        ['अझै भात थप्नुहोस्।', 'ajhai bhāta thapnuhos', 'more rice please'],
        ['बिल दिनुहोस् न।', 'bila dinuhos na', 'the bill please'],
        ['खाना एकदम मीठो भयो।', 'khānā ekadama mīṭho bhayo', 'the food was delicious'],
        ['यो केको तरकारी हो?', 'yo keko tarakārī ho?', 'what vegetable dish is this?'],
        ['ताजा छ कि छैन?', 'tājā chha ki chhaina?', 'is it fresh or not?'],
        ['तातो पानी मिल्छ?', 'tāto pānī milchha?', 'can I get hot water?'],
        ['चिसो पानी दिनुहोस्।', 'chiso pānī dinuhos', 'cold water please'],
        ['एक प्लेट मम दिनुहोस्।', 'eka pleṭa mama dinuhos', 'one plate of momos please'],
        ['खाजा खान जाऔँ।', 'khājā khāna jāaũ', "let's go have a snack"],
        ['भोक लाग्यो।', 'bhoka lāgyo', 'I am hungry'],
        ['तिर्खा लाग्यो।', 'tirkhā lāgyo', 'I am thirsty'],
        ['यहाँ बसेर खाने हो?', 'yahā̃ basera khāne ho?', 'eating here?'],
        ['लैजान प्याक गरिदिनुहोस्।', 'laijāna pyāka garidinuhos', 'please pack it to take away'],
    ]},
    {id: 'smalltalk', label: 'People & small talk', phrases: [
        ['तपाईंको नाम के हो?', 'tapāīṁko nāma ke ho?', 'what is your name?'],
        ['तपाईंलाई भेटेर खुसी लाग्यो।', 'tapāīṁlāī bheṭera khusī lāgyo', 'nice to meet you'],
        ['तपाईं कहाँबाट आउनुभएको?', 'tapāīṁ kahā̃bāṭa āunubhaeko?', 'where are you from?'],
        ['म विदेशबाट आएको हुँ।', 'ma wideshabāṭa āeko hũ', 'I came from abroad'],
        ['म काठमाडौंमा बस्छु।', 'ma kāṭhamāḍauṁmā baschhu', 'I live in kathmandu'],
        ['तपाईं के गर्नुहुन्छ?', 'tapāīṁ ke garnuhunchha?', 'what do you do?'],
        ['म विद्यार्थी हुँ।', 'ma widyārthī hũ', 'I am a student'],
        ['म कला पढ्छु।', 'ma kalā paḍhchhu', 'I study art'],
        ['तपाईंको घर कता हो?', 'tapāīṁko ghara katā ho?', 'where is your home?'],
        ['परिवारमा को को हुनुहुन्छ?', 'pariwāramā ko ko hunuhunchha?', 'who is in your family?'],
        ['तपाईंलाई नेपाल कस्तो लाग्यो?', 'tapāīṁlāī nepāla kasto lāgyo?', 'how do you like nepal?'],
        ['नेपाल धेरै राम्रो लाग्छ।', 'nepāla dherai rāmro lāgchha', 'I like nepal very much'],
        ['नेपाली भाषा सिक्दै छु।', 'nepālī bhāṣā sikdai chhu', 'I am learning the nepali language'],
        ['तपाईंको उमेर कति भयो?', 'tapāīṁko umera kati bhayo?', 'how old are you?'],
        ['म भर्खरै आएको हुँ।', 'ma bharkharai āeko hũ', 'I arrived just recently'],
        ['यहाँ मौसम राम्रो छ।', 'yahā̃ mausama rāmro chha', 'the weather is nice here'],
        ['आज पानी पर्ला जस्तो छ।', 'āja pānī parlā jasto chha', 'it looks like rain today'],
        ['तपाईंसँग कुरा गर्न रमाइलो भयो।', 'tapāīṁsãga kurā garna ramāilo bhayo', 'it was fun talking with you'],
        ['फोन नम्बर दिनुहोस् न।', 'phona nambara dinuhos na', 'your phone number please'],
        ['पछि कुरा गरौँला।', 'pachhi kurā garaũlā', "let's talk later"],
        ['को हुनुहुन्छ हजुर?', 'ko hunuhunchha hajura?', 'who is it please?'],
        ['एकदम रमाइलो भयो।', 'ekadama ramāilo bhayo', 'it was great fun'],
        ['बिहे भयो?', 'bihe bhayo?', 'are you married?'],
        ['हामी सँगै आएका हौँ।', 'hāmī sãgai āekā haũ', 'we came together'],
        ['घुम्न जाऔँ है।', 'ghumna jāaũ hai', "let's go for a stroll"],
    ]},
    {id: 'questions', label: 'Question words', phrases: [
        ['यो के हो?', 'yo ke ho?', 'what is this?'],
        ['त्यो के हो?', 'tyo ke ho?', 'what is that?'],
        ['को आउनुभयो?', 'ko āunubhayo?', 'who came?'],
        ['यो कसको हो?', 'yo kasako ho?', 'whose is this?'],
        ['कसलाई दिने?', 'kasalāī dine?', 'to whom shall I give it?'],
        ['कहाँ जानुहुन्छ?', 'kahā̃ jānuhunchha?', 'where are you going?'],
        ['कता जाने?', 'katā jāne?', 'which way to go?'],
        ['कहिले फर्कनुहुन्छ?', 'kahile pharkanuhunchha?', 'when will you return?'],
        ['किन ढिलो भयो?', 'kina ḍhilo bhayo?', 'why is it late?'],
        ['कसरी जाने?', 'kasarī jāne?', 'how to get there?'],
        ['कति चाहिन्छ?', 'kati chāhinchha?', 'how much is needed?'],
        ['कति जना हुनुहुन्छ?', 'kati janā hunuhunchha?', 'how many people are you?'],
        ['कुन राम्रो छ?', 'kuna rāmro chha?', 'which one is good?'],
        ['कुन चाहिँ लिने?', 'kuna chāhĩ line?', 'which one to take?'],
        ['के भयो?', 'ke bhayo?', 'what happened?'],
        ['केही भएन।', 'kehī bhaena', 'nothing happened'],
        ['के गर्ने त?', 'ke garne ta?', 'so what to do?'],
        ['कोसँग जाने?', 'kosãga jāne?', 'with whom to go?'],
        ['कहाँबाट आउनुभयो?', 'kahā̃bāṭa āunubhayo?', 'where did you come from?'],
        ['कहिलेदेखि खुल्छ?', 'kahiledekhi khulchha?', 'from when is it open?'],
        ['कतिसम्म बस्नुहुन्छ?', 'katisamma basnuhunchha?', 'until when will you stay?'],
        ['किनभने समय छैन।', 'kinabhane samaya chhaina', 'because there is no time'],
        ['केका लागि?', 'kekā lāgi?', 'for what?'],
        ['कस्तो छ?', 'kasto chha?', 'how is it?'],
        ['यस्तो किन भयो?', 'yasto kina bhayo?', 'why did it happen like this?'],
    ]},
    {id: 'grammar', label: 'Grammar patterns', phrases: [
        ['जानु अघि भन्नुहोस्।', 'jānu aghi bhannuhos', 'tell me before going'],
        ['खाए पछि जाऔँला।', 'khāe pachhi jāaũlā', 'we will go after eating'],
        ['काम गरे पछि आराम।', 'kāma gare pachhi ārāma', 'rest after work'],
        ['पानी परे पनि जान्छु।', 'pānī pare pani jānchhu', "I'll go even if it rains"],
        ['यदि समय भए आउनुहोस्।', 'yadi samaya bhae āunuhos', 'come if you have time'],
        ['भोक लागे खानुहोस्।', 'bhoka lāge khānuhos', 'eat if you are hungry'],
        ['मलाई चिया मन पर्छ।', 'malāī chiyā mana parchha', 'I like tea'],
        ['मलाई हिँड्न मन लाग्छ।', 'malāī hĩḍna mana lāgchha', 'I feel like walking'],
        ['मलाई मद्दत चाहिन्छ।', 'malāī maddata chāhinchha', 'I need help'],
        ['मलाई नेपाली सिक्नु छ।', 'malāī nepālī siknu chha', 'I have to learn nepali'],
        ['म पढ्न सक्छु।', 'ma paḍhna sakchhu', 'I can read'],
        ['म लेख्न सक्दिनँ।', 'ma lekhna sakdinã', 'I cannot write'],
        ['अब जानु पर्छ।', 'aba jānu parchha', 'I must go now'],
        ['गर्नु पर्दैन।', 'garnu pardaina', 'no need to do it'],
        ['एउटा मात्र छ।', 'euṭā mātra chha', 'there is only one'],
        ['म पनि आउँछु।', 'ma pani āũchhu', 'I will come too'],
        ['सायद भोलि आउँला।', 'sāyada bholi āũlā', "maybe I'll come tomorrow"],
        ['पक्कै आउनुहोस् है।', 'pakkai āunuhos hai', 'do come for sure'],
        ['किनभने भोलि बिदा छ।', 'kinabhane bholi bidā chha', 'because tomorrow is a holiday'],
        ['तर आज मिल्दैन।', 'tara āja mildaina', 'but today it is not possible'],
        ['अथवा भोलि गरौँला।', 'athawā bholi garaũlā', "or we'll do it tomorrow"],
        ['यो त्यो भन्दा ठूलो छ।', 'yo tyo bhandā ṭhūlo chha', 'this is bigger than that'],
        ['सबै भन्दा राम्रो यो हो।', 'sabai bhandā rāmro yo ho', 'this is the best of all'],
        ['बिस्तारै बिस्तारै सिक्दै छु।', 'bistārai bistārai sikdai chhu', 'I am learning little by little'],
        ['गर्दै छु हजुर।', 'gardai chhu hajura', 'I am doing it'],
        ['भन्न खोजेको के हो?', 'bhanna khojeko ke ho?', 'what are you trying to say?'],
        ['जस्तो तपाईं भन्नुहुन्छ।', 'jasto tapāīṁ bhannuhunchha', 'as you say'],
        ['मलाई लाग्छ हुन्छ।', 'malāī lāgchha hunchha', 'I think it will be fine'],
        ['हुन सक्छ नि।', 'huna sakchha ni', 'it is possible'],
        ['अझै सिक्दै छु।', 'ajhai sikdai chhu', 'I am still learning'],
    ]},
    {id: 'artschool', label: 'Art school & craft', phrases: [
        ['कक्षा कति बजे सुरु हुन्छ?', 'kakshā kati baje suru hunchha?', 'when does the class start?'],
        ['कक्षा कति बजे सकिन्छ?', 'kakshā kati baje sakinchha?', 'when does the class end?'],
        ['काम कहिले बुझाउने?', 'kāma kahile bujhāune?', 'when to submit the work?'],
        ['यो कसरी बनाउने?', 'yo kasarī banāune?', 'how to make this?'],
        ['एकपटक देखाउनुहोस् न।', 'ekapaṭaka dekhāunuhos na', 'please show me once'],
        ['यो कुन सामग्री हो?', 'yo kuna sāmagrī ho?', 'what material is this?'],
        ['यो काठको हो।', 'yo kāṭhako ho', 'this is made of wood'],
        ['यो माटोको भाँडा हो।', 'yo māṭoko bhā̃ḍā ho', 'this is a clay pot'],
        ['धातुको काम गाह्रो छ।', 'dhātuko kāma gāhro chha', 'metalwork is difficult'],
        ['कपडा कहाँ किन्ने?', 'kapaḍā kahā̃ kinne?', 'where do I buy fabric?'],
        ['धागो र सियो दिनुहोस्।', 'dhāgo ra siyo dinuhos', 'thread and needle please'],
        ['बाँसको काम सिक्दै छु।', 'bā̃sako kāma sikdai chhu', 'I am learning bamboo craft'],
        ['कागजमा पहिला कोर्नुहोस्।', 'kāgajamā pahilā kornuhos', 'draw on paper first'],
        ['रङ अलि गाढा भयो।', 'raṅa ali gāḍhā bhayo', 'the color got a bit dark'],
        ['कुन रङ राम्रो देखिन्छ?', 'kuna raṅa rāmro dekhinchha?', 'which color looks good?'],
        ['यो औजार केका लागि?', 'yo aujāra kekā lāgi?', 'what is this tool for?'],
        ['काट्ने कसरी हो?', 'kāṭne kasarī ho?', 'how do I cut it?'],
        ['यहाँ जोड्ने हो?', 'yahā̃ joḍne ho?', 'do I join it here?'],
        ['बुन्न सिकाउनुहोस् न।', 'bunna sikāunuhos na', 'please teach me to weave'],
        ['सिउन गाह्रो रहेछ।', 'siuna gāhro rahechha', 'sewing turns out to be hard'],
        ['कुँद्ने काम मन पर्छ।', 'kũdne kāma mana parchha', 'I like carving work'],
        ['नमुना हेरेर बनाउनुहोस्।', 'namunā herera banāunuhos', 'make it following the sample'],
        ['मेरो डिजाइन यस्तो छ।', 'mero ḍijāina yasto chha', 'my design is like this'],
        ['यो ठीक भयो कि भएन?', 'yo ṭhīka bhayo ki bhaena?', 'did it come out right or not?'],
        ['फेरि गर्नु पर्छ?', 'pheri garnu parchha?', 'do I have to redo it?'],
        ['अलि मिलेन जस्तो छ।', 'ali milena jasto chha', 'it does not quite fit, it seems'],
        ['गुरुलाई सोधौँला।', 'gurulāī sodhaũlā', "let's ask the teacher"],
        ['आज चित्र बनाउने दिन हो।', 'āja chitra banāune dina ho', 'today is drawing day'],
        ['मूर्ति बनाउन गाह्रो छ।', 'mūrti banāuna gāhro chha', 'making a sculpture is hard'],
        ['काम सकियो हजुर।', 'kāma sakiyo hajura', 'the work is finished'],
    ]},
];
